In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "data/raw/censo_exemplo.csv",  
    sep=";",                        
    encoding="latin-1"
)

In [3]:
df.head()

,NU_ANO_CENSO,TP_MODALIDADE_ENSINO,CO_REGIAO,QT_MATRICULA_TOTAL,TP_SITUACAO
0,2023,1,3,120.0,1
1,2023,2,3,340.0,1
2,2023,1,2,80.0,1
3,2023,2,2,210.0,1
4,2022,1,3,115.0,1

In [4]:
linhas, colunas = df.shape

print(f"Linhas:  {linhas}")
print(f"Colunas: {colunas}")

Linhas:  7
Colunas: 5

In [5]:
df.dtypes

NU_ANO_CENSO              int64
TP_MODALIDADE_ENSINO      int64
CO_REGIAO                 int64
QT_MATRICULA_TOTAL      float64
TP_SITUACAO               int64
dtype: object

In [6]:
contagem_faltando = df.isnull().sum()

print("Valores faltando por coluna:")
print(contagem_faltando)

Valores faltando por coluna:
NU_ANO_CENSO            0
TP_MODALIDADE_ENSINO    0
CO_REGIAO               0
QT_MATRICULA_TOTAL      1
TP_SITUACAO             0
dtype: int64

In [7]:
so_as_com_problema = contagem_faltando[contagem_faltando > 0]
print(so_as_com_problema)

QT_MATRICULA_TOTAL    1
dtype: int64

In [8]:
df.describe()

,NU_ANO_CENSO,TP_MODALIDADE_ENSINO,CO_REGIAO,QT_MATRICULA_TOTAL,TP_SITUACAO
count,7.000000,7.000000,7.000000,6.000000,7.0
mean,2022.571429,1.428571,2.571429,192.500000,1.0
std,0.534522,0.534522,0.534522,105.344672,0.0
min,2022.000000,1.000000,2.000000,80.000000,1.0
25%,2022.000000,1.000000,2.000000,116.250000,1.0
50%,2023.000000,1.000000,3.000000,165.000000,1.0
75%,2023.000000,2.000000,3.000000,270.000000,1.0
max,2023.000000,2.000000,3.000000,340.000000,1.0

In [9]:
resultado = df.groupby("TP_MODALIDADE_ENSINO")["QT_MATRICULA_TOTAL"].sum()

print(resultado)

TP_MODALIDADE_ENSINO
1    315.0
2    840.0
Name: QT_MATRICULA_TOTAL, dtype: float64